#!/usr/bin/env bash

script_dir=$( cd "$( dirname "$0" )" && pwd )
cd $script_dir/test
clear

files=$1
if [[ $files == "" ]]; then
  files="$(ls *_test.py | sed -e 's/\..*$//')"
fi

# Run
python3 -m unittest helpers/test_helper.py $files

cd $script_dir

# Cleanup
find -d . | grep "__pycache__$" | xargs rm -rf
