#!/usr/bin/env bash

script_dir=$( cd "$( dirname "$0" )" && pwd )
timestamp=$(date +%s)
delay=$1

if [[ $2 == "clean" ]]; then
  for f in $(ls /tmp/cache-invoke-* 2>/dev/null)
  do
    f_timestamp=$(echo $f | awk -F"-" '{print $NF}')
    if [[ $timestamp > $(($f_timestamp + $delay)) ]]; then
      rm $f
    fi
  done
  exit 0
fi

cmd="${@: 2}"
md5=$(echo $cmd | md5)
filename="/tmp/cache-invoke-$md5-$timestamp"

existing=$(ls /tmp/cache-invoke-$md5-* 2>/dev/null)
if [[ $? == 0 ]]; then
  existing_timestamp=$(echo $existing | awk -F"-" '{print $NF}')
  if [[ $timestamp > $((existing_timestamp + $delay)) ]]; then
    rm $existing
  else
    cat $existing
    exit 0
  fi
fi

$cmd >$filename 2>&1
cat $filename
$script_dir/cached-invoke $delay clean &
